version: '2'

services:
    lbss:
        image: localhost:5000/lbss-sba
        ports:
            - 8080:8080
            - 2121:2121
            - 30000-31000:30000-31000

    lbss-db:
        image: localhost:5000/lbss-db
        ports:
            - 27017:27017
