version: '2'

services:
    lbss:
        image: gimatdinov/lbss-sba
        ports:
            - 8080:8080
            - 2121:2121
        volumes:
            - lbssLOG:/var/log/lbss
            - lbssFTP:/data/ftp

    lbss-db:
        image: gimatdinov/lbss-db
        ports:
            - 27017:27017
        volumes:
            - lbssDB:/data/db
            
volumes:
    lbssLOG:
    lbssFTP:
    lbssDB: